version: 0.2

run-as: root


phases:
   pre_build:
     commands:
       - apt update && sudo apt upgrade -y
       - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
       - apt install nodejs nginx -y
       - npm install npm@latest -g
       - npm install pm2@latest -g
       - npm install --save dotenv
       - echo "MONGODB_URI_PRAJWAL=$MONGODB_URI_PRAJWAL" > .env

   build:
     commands:
        - echo "Build of nodejs backend application successfull"
       

artifacts:
  files:
    - echo "Upload artifacts to bucket for Codedeploy"
    - '**/*'
